"""
One-shot backfill: populate the franchise resolver tables from the raw
lineage / shared_universe / recognized_subgroups columns already stored in
``public.movie_franchise_metadata``.

Run once after rebuilding Postgres with the new schema (or after ALTER/CREATE
for a pre-existing database). Safe to re-run: all writes use ON CONFLICT DO
NOTHING or a truncate-then-rebuild cycle, so iteration is idempotent.

Pipeline:
  1. ALTER/CREATE — add the two movie_card columns + GIN indexes, the new
     lex tables (franchise_entry, franchise_token), the DF materialized
     view, and drop the legacy lex.inv_franchise_postings table.
     IF NOT EXISTS / IF EXISTS throughout; no-op on fresh-init DBs that
     already got these from 01_create_postgres_tables.sql.
  2. Wipe every table/column the backfill writes — truncate
     lex.franchise_token, lex.franchise_entry (RESTART IDENTITY CASCADE),
     and reset the two movie_card columns to '{}'. The prior data (if any)
     is treated as wrong: normalization rules are new, and merging would
     leave stale rows behind.
  3. Enumerate movies from public.movie_card.
  4. Read each movie's lineage / shared_universe / recognized_subgroups
     directly from public.movie_franchise_metadata (no tracker dependency —
     the raw strings are persisted on the row).
  5. For each movie, call write_franchise_data — which upserts
     franchise_entry rows, writes franchise_token rows, and returns the two
     entry-id arrays we stamp onto movie_card.

Batched commits every COMMIT_EVERY movies so a mid-run failure loses at
most one batch.
"""
from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

import psycopg
from dotenv import load_dotenv

from db.postgres import (
    pool,
    refresh_franchise_token_doc_frequency,
    update_movie_card_franchise_ids,
)
from movie_ingestion.final_ingestion.ingest_movie import write_franchise_data

load_dotenv()

# Batch size controls commit granularity. 200 keeps each transaction small
# enough to avoid long idle_in_transaction windows while still amortizing
# round-trip overhead on ~100K movies. Same as the studio backfill.
COMMIT_EVERY = 200


def _sync_connect() -> psycopg.Connection:
    """Open a sync psycopg connection for one-off DDL statements."""
    return psycopg.connect(
        host=os.getenv("POSTGRES_HOST"),
        port=int(os.getenv("POSTGRES_PORT", "5432")),
        user=os.getenv("POSTGRES_USER"),
        password=os.getenv("POSTGRES_PASSWORD"),
        dbname=os.getenv("POSTGRES_DB"),
    )


def _apply_schema_migrations() -> None:
    """
    Ensure the new tables, indexes, columns, and materialized view exist,
    and drop the legacy franchise postings table.

    IF NOT EXISTS / IF EXISTS everywhere so this is a no-op on a database
    that was freshly initialized from 01_create_postgres_tables.sql. All
    statements are safe to run repeatedly.
    """
    with _sync_connect() as conn:
        conn.autocommit = True
        with conn.cursor() as cur:
            print("Step 1/5: applying schema migrations...")

            # New movie_card columns + GIN indexes.
            cur.execute(
                """
                ALTER TABLE public.movie_card
                  ADD COLUMN IF NOT EXISTS franchise_name_entry_ids BIGINT[] NOT NULL DEFAULT '{}'
                """
            )
            cur.execute(
                """
                ALTER TABLE public.movie_card
                  ADD COLUMN IF NOT EXISTS subgroup_entry_ids BIGINT[] NOT NULL DEFAULT '{}'
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_movie_card_franchise_name_entry_ids
                  ON public.movie_card USING GIN (franchise_name_entry_ids)
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_movie_card_subgroup_entry_ids
                  ON public.movie_card USING GIN (subgroup_entry_ids)
                """
            )

            # New registry + inverted index.
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS lex.franchise_entry (
                  franchise_entry_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  canonical_string    TEXT NOT NULL,
                  normalized_string   TEXT NOT NULL UNIQUE
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS lex.franchise_token (
                  token               TEXT   NOT NULL,
                  franchise_entry_id  BIGINT NOT NULL REFERENCES lex.franchise_entry ON DELETE CASCADE,
                  PRIMARY KEY (token, franchise_entry_id)
                )
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_franchise_token_entry
                  ON lex.franchise_token (franchise_entry_id)
                """
            )

            # DF materialized view + unique index (needed for CONCURRENT refresh).
            cur.execute(
                """
                CREATE MATERIALIZED VIEW IF NOT EXISTS lex.franchise_token_doc_frequency AS
                SELECT
                  token,
                  COUNT(*)::BIGINT AS doc_frequency,
                  now()            AS updated_at
                FROM lex.franchise_token
                GROUP BY token
                """
            )
            cur.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS idx_franchise_token_df_token
                  ON lex.franchise_token_doc_frequency (token)
                """
            )

            # Drop the legacy franchise postings table. CASCADE handles the
            # secondary index + any dependent views (none expected, but
            # safer than a bare DROP). Idempotent via IF EXISTS.
            cur.execute("DROP TABLE IF EXISTS lex.inv_franchise_postings CASCADE")


async def _wipe_franchise_data() -> None:
    """
    Clear every table/column the backfill is about to rewrite.

    The prior run(s) wrote through the legacy ``lex.inv_franchise_postings``
    path (now dropped) and did not populate ``lex.franchise_entry`` /
    ``lex.franchise_token`` / the two new movie_card columns at all, so
    there is typically nothing to clear on first run. On a re-run, the
    previous normalization may differ from the current one, so stale rows
    are treated as wrong rather than merge-able.

    Ordering:
      1. ``lex.franchise_token`` — child of ``lex.franchise_entry`` via
         ON DELETE CASCADE. Truncate first so the parent truncate doesn't
         have to drive the cascade.
      2. ``lex.franchise_entry`` — ``RESTART IDENTITY`` so reissued ids
         start from 1 on the clean slate. Only outside references are the
         two movie_card columns, which step 3 clears.
      3. ``public.movie_card.franchise_name_entry_ids`` /
         ``subgroup_entry_ids`` — bulk reset to ``'{}'`` in one UPDATE so
         any card row the loop skips is left in a consistent empty state
         rather than pointing at franchise_entry ids that no longer exist.

    All three statements run in a single transaction so a mid-wipe failure
    cannot leave the schema half-cleared.
    """
    print("Step 2/5: wiping existing franchise data (tables + movie_card arrays)...")
    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute("TRUNCATE TABLE lex.franchise_token")
            await cur.execute("TRUNCATE TABLE lex.franchise_entry RESTART IDENTITY CASCADE")
            await cur.execute(
                "UPDATE public.movie_card "
                "SET franchise_name_entry_ids = '{}', subgroup_entry_ids = '{}' "
                "WHERE franchise_name_entry_ids <> '{}' "
                "   OR subgroup_entry_ids <> '{}'"
            )
        await conn.commit()
    print("  Franchise tables truncated and movie_card arrays reset.")


async def _load_franchise_rows() -> dict[
    int, tuple[str | None, str | None, list[str]]
]:
    """
    Read ``(lineage, shared_universe, recognized_subgroups)`` for every
    movie that has a ``movie_franchise_metadata`` row.

    The raw TEXT columns are the authoritative source here — we do NOT
    round-trip through the tracker's FranchiseOutput JSON. Re-normalizing
    the stored strings is idempotent with what Stage 6 produced, and this
    keeps the backfill DB-only (no tracker-availability requirement).
    """
    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                SELECT movie_id, lineage, shared_universe, recognized_subgroups
                FROM public.movie_franchise_metadata
                """
            )
            rows = await cur.fetchall()

    out: dict[int, tuple[str | None, str | None, list[str]]] = {}
    for movie_id, lineage, shared_universe, recognized_subgroups in rows:
        # recognized_subgroups column is TEXT[] NOT NULL DEFAULT '{}', so
        # psycopg always returns a list here (never None).
        out[int(movie_id)] = (lineage, shared_universe, list(recognized_subgroups))
    return out


async def _load_movie_ids_from_card() -> list[int]:
    """Fetch every tmdb_id present in movie_card so we only backfill live rows."""
    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute("SELECT movie_id FROM public.movie_card ORDER BY movie_id")
            rows = await cur.fetchall()
    return [int(row[0]) for row in rows]


async def _run_backfill() -> None:
    """
    Main async pass: iterate movies, resolve franchise entries/tokens, stamp
    the two movie_card arrays.

    Uses a fresh connection per batch so the idle_in_transaction timeout
    (2 min per 01_create_postgres_tables.sql) can't kill us on large runs.

    Pool lifecycle is owned here — the module-level ``pool`` is created with
    ``open=False`` in db.postgres, so we must open it inside the running
    event loop. Closing inside the same loop's ``finally`` prevents the
    "pool bound to a closed loop" RuntimeError.
    """
    await pool.open()
    try:
        # Wipe first so the per-movie loop runs on a clean slate.
        await _wipe_franchise_data()

        print("Step 3/5: loading franchise metadata rows...")
        franchise = await _load_franchise_rows()
        print(f"  Loaded {len(franchise):,} movie_franchise_metadata rows.")

        print("Step 4/5: loading movie_card ids...")
        movie_ids = await _load_movie_ids_from_card()
        print(f"  Found {len(movie_ids):,} movies in public.movie_card.")

        print(f"Step 5/5: backfilling franchise data (batches of {COMMIT_EVERY})...")
        total = len(movie_ids)
        processed = 0
        missing_metadata = 0

        # Batch outer loop: one async transaction per COMMIT_EVERY movies.
        for batch_start in range(0, total, COMMIT_EVERY):
            batch = movie_ids[batch_start : batch_start + COMMIT_EVERY]
            async with pool.connection() as conn:
                try:
                    for movie_id in batch:
                        row = franchise.get(movie_id)
                        if row is None:
                            # movie_card row with no franchise metadata —
                            # common (most movies have no franchise). Stamp
                            # empty arrays so the card column state is always
                            # consistent with the registry.
                            missing_metadata += 1
                            name_ids: list[int] = []
                            subgroup_ids: list[int] = []
                        else:
                            lineage, shared_universe, subgroups = row
                            name_ids, subgroup_ids = await write_franchise_data(
                                lineage,
                                shared_universe,
                                subgroups,
                                conn=conn,
                            )
                        # Backfill path: movie_card already exists, so we
                        # UPDATE the two arrays in place rather than
                        # re-upserting the whole card row.
                        await update_movie_card_franchise_ids(
                            movie_id, name_ids, subgroup_ids, conn=conn
                        )
                    await conn.commit()
                except Exception as e:
                    await conn.rollback()
                    print(f"  Batch starting at {batch_start} failed: {e}")
                    raise

            processed += len(batch)
            if processed % (COMMIT_EVERY * 10) == 0 or processed == total:
                print(f"  {processed:,} / {total:,} movies backfilled")

        if missing_metadata:
            print(
                f"Note: {missing_metadata} movies had a movie_card row but no "
                "movie_franchise_metadata — stamped with empty arrays."
            )

        # Refresh the franchise-token DF materialized view so downstream
        # query-side DF-ceiling filtering reflects the newly written rows.
        # Same post-run step the studio backfill does.
        print("Refreshing lex.franchise_token_doc_frequency...")
        await refresh_franchise_token_doc_frequency()

        print("Backfill complete.")
    finally:
        await pool.close()


def main() -> None:
    _apply_schema_migrations()
    asyncio.run(_run_backfill())


if __name__ == "__main__":
    sys.exit(main())
