"""
One-shot backfill: populate lex.award_name_entry, lex.award_name_token,
and public.movie_awards.award_name_entry_id from the existing
public.movie_awards.award_name column.

Run once after rebuilding Postgres with the new schema (or after the
ALTER/CREATE statements below on a pre-existing database). Safe to
re-run: every write is either a truncate-then-fill cycle or an ON
CONFLICT DO NOTHING upsert.

Unlike backfill_production_brands_and_companies.py, this script does not
iterate per-movie. The source of truth for raw award names already lives
in Postgres (``public.movie_awards.award_name``), the cardinality of
distinct names is tiny (~600 today), and the only per-row work is
updating ``award_name_entry_id`` by joining on the raw string — which
Postgres can do server-side in one UPDATE. Three bulk SQL statements
plus one Python normalization pass, no per-movie loop.

Pipeline:
  1. ALTER/CREATE — add the movie_awards column, new lex tables, the
     DF materialized view, and all supporting indexes. IF NOT EXISTS
     throughout; no-op on fresh-init DBs that already got these from
     01_create_postgres_tables.sql.
  2. Wipe every table/column the backfill writes — TRUNCATE
     lex.award_name_token, TRUNCATE lex.award_name_entry RESTART
     IDENTITY CASCADE, and UPDATE public.movie_awards SET
     award_name_entry_id = NULL. Prior data is treated as wrong
     (normalization/tokenization rules may have changed); merging would
     leave stale rows behind.
  3. Populate entry + token tables from the distinct
     ``public.movie_awards.award_name`` values, computing normalized
     form and tokens in Python via implementation/misc/award_name_text.
  4. Stamp ``award_name_entry_id`` onto every ``public.movie_awards``
     row via a single UPDATE driven by a ``VALUES (raw, entry_id)``
     map. One round trip; ~600 rows in the mapping keeps the parameter
     count modest.
  5. REFRESH MATERIALIZED VIEW lex.award_name_token_doc_frequency so
     the DF-ceiling review can run on the fresh bucket distribution.
"""
from __future__ import annotations

import asyncio
import os
import sys

import psycopg
from dotenv import load_dotenv

from db.postgres import (
    pool,
    batch_upsert_award_name_entries,
    batch_insert_award_name_tokens,
    refresh_award_name_token_doc_frequency,
)
from implementation.misc.award_name_text import (
    normalize_award_string,
    tokenize_award_string,
)

load_dotenv()


def _sync_connect() -> psycopg.Connection:
    """Open a sync psycopg connection for one-off DDL statements."""
    return psycopg.connect(
        host=os.getenv("POSTGRES_HOST"),
        port=int(os.getenv("POSTGRES_PORT", "5432")),
        user=os.getenv("POSTGRES_USER"),
        password=os.getenv("POSTGRES_PASSWORD"),
        dbname=os.getenv("POSTGRES_DB"),
    )


def _apply_schema_migrations() -> None:
    """
    Ensure the new lex tables, DF materialized view, and
    movie_awards.award_name_entry_id column exist.

    IF NOT EXISTS everywhere so this is a no-op on a database that was
    freshly initialized from 01_create_postgres_tables.sql. All statements
    are safe to run repeatedly.
    """
    with _sync_connect() as conn:
        conn.autocommit = True
        with conn.cursor() as cur:
            print("Step 1/5: applying schema migrations...")

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS lex.award_name_entry (
                  award_name_entry_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  normalized           TEXT NOT NULL UNIQUE
                )
                """
            )

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS lex.award_name_token (
                  token                TEXT NOT NULL,
                  award_name_entry_id  INT  NOT NULL REFERENCES lex.award_name_entry ON DELETE CASCADE,
                  PRIMARY KEY (token, award_name_entry_id)
                )
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_award_name_token_entry
                  ON lex.award_name_token (award_name_entry_id)
                """
            )

            cur.execute(
                """
                CREATE MATERIALIZED VIEW IF NOT EXISTS lex.award_name_token_doc_frequency AS
                SELECT
                  token,
                  COUNT(*)::BIGINT AS doc_frequency,
                  now()            AS updated_at
                FROM lex.award_name_token
                GROUP BY token
                """
            )
            cur.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS idx_award_name_token_df_token
                  ON lex.award_name_token_doc_frequency (token)
                """
            )

            cur.execute(
                """
                ALTER TABLE public.movie_awards
                  ADD COLUMN IF NOT EXISTS award_name_entry_id INT
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_awards_entry
                  ON public.movie_awards (award_name_entry_id)
                """
            )


async def _wipe_award_name_data() -> None:
    """
    Clear every table/column the backfill is about to rewrite.

    Prior run(s) may have used different normalization or tokenization
    rules; stale rows are treated as wrong rather than merge-able. Step 3
    rebuilds the data from ``public.movie_awards.award_name``.

    Ordering:
      1. ``lex.award_name_token`` — child of ``lex.award_name_entry`` via
         ON DELETE CASCADE. Truncated first so the parent truncate doesn't
         have to drive the cascade.
      2. ``lex.award_name_entry`` — ``RESTART IDENTITY`` so reissued ids
         start from 1 on the clean slate.
      3. ``public.movie_awards.award_name_entry_id`` — bulk NULL-out so
         Step 4's UPDATE-FROM-VALUES can detect coverage by counting
         remaining NULLs.

    All three statements run in a single transaction so a mid-wipe
    failure cannot leave the schema half-cleared.
    """
    print("Step 2/5: wiping existing award-name data (entry + token + movie_awards.award_name_entry_id)...")
    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute("TRUNCATE TABLE lex.award_name_token")
            await cur.execute("TRUNCATE TABLE lex.award_name_entry RESTART IDENTITY CASCADE")
            await cur.execute(
                "UPDATE public.movie_awards "
                "SET award_name_entry_id = NULL "
                "WHERE award_name_entry_id IS NOT NULL"
            )
        await conn.commit()
    print("  Award-name tables truncated and movie_awards.award_name_entry_id cleared.")


async def _load_distinct_award_names() -> list[str]:
    """Fetch every distinct raw award_name string from public.movie_awards."""
    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                "SELECT DISTINCT award_name FROM public.movie_awards "
                "WHERE award_name IS NOT NULL "
                "ORDER BY award_name"
            )
            rows = await cur.fetchall()
    return [str(row[0]) for row in rows]


async def _populate_entries_and_tokens(raw_names: list[str]) -> dict[str, int]:
    """
    Upsert lex.award_name_entry + lex.award_name_token from the given raw
    names and return ``{raw_name: award_name_entry_id}``.

    Rows whose raw string normalizes to the empty string (punctuation-
    only edge cases) are omitted from the return map — the caller treats
    those as "no entry id" and the nullable column stays NULL for those
    movie_awards rows.
    """
    # Normalize each raw name once; memoize so we pass the same string to
    # both the entry upsert and the per-raw entry-id map built below.
    normalized_by_raw: dict[str, str] = {}
    for raw in raw_names:
        normalized_by_raw[raw] = normalize_award_string(raw)

    unique_normalized = sorted({n for n in normalized_by_raw.values() if n})
    print(
        f"  {len(raw_names):,} distinct raw award_name values → "
        f"{len(unique_normalized):,} distinct normalized entries."
    )

    async with pool.connection() as conn:
        entry_id_map = await batch_upsert_award_name_entries(
            unique_normalized, conn=conn,
        )

        # Build (token, entry_id) pairs for every normalized string.
        token_rows: set[tuple[str, int]] = set()
        for normalized in unique_normalized:
            eid = entry_id_map.get(normalized)
            if eid is None:
                continue
            for token in tokenize_award_string(normalized, already_normalized=True):
                token_rows.add((token, eid))

        await batch_insert_award_name_tokens(list(token_rows), conn=conn)
        await conn.commit()

    print(
        f"  Inserted {len(entry_id_map):,} entry rows, "
        f"{len(token_rows):,} (token, entry_id) pairs."
    )

    # Compose the per-raw-name → entry_id mapping the caller needs for
    # stamping. Empties and any normalized strings the upsert didn't
    # return are dropped.
    raw_to_entry: dict[str, int] = {}
    for raw, normalized in normalized_by_raw.items():
        if not normalized:
            continue
        eid = entry_id_map.get(normalized)
        if eid is None:
            continue
        raw_to_entry[raw] = eid
    return raw_to_entry


async def _stamp_movie_awards(raw_to_entry: dict[str, int]) -> None:
    """
    Bulk-UPDATE public.movie_awards.award_name_entry_id via a VALUES map.

    Postgres can't compute ``normalize_award_string`` in SQL (NFKD fold,
    punctuation strip, ordinal + cardinal number-to-word happen in
    Python), so we drive the UPDATE with an in-query mapping built from
    the distinct-name scan in Step 3.

    One round trip. With ~600 distinct raw names the parameter list is
    ~1,200 values — well inside libpq's 65,535-parameter limit.
    """
    if not raw_to_entry:
        print("  No raw→entry mappings produced; skipping movie_awards stamp.")
        return

    items = list(raw_to_entry.items())
    # One (%s, %s) tuple per mapping row.
    values_template = ", ".join(["(%s, %s)"] * len(items))
    query = f"""
    UPDATE public.movie_awards ma
       SET award_name_entry_id = m.entry_id
      FROM (VALUES {values_template}) AS m(raw, entry_id)
     WHERE ma.award_name = m.raw
    """
    flat_params: list = []
    for raw, eid in items:
        flat_params.extend([raw, eid])

    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(query, flat_params)
            updated = cur.rowcount
        await conn.commit()
    print(f"  Stamped award_name_entry_id on {updated:,} movie_awards rows.")


async def _report_unstamped() -> None:
    """Log how many movie_awards rows still have a NULL entry id post-stamp.

    Expect a small residual only for award_name strings that normalize to
    the empty string (punctuation-only inputs) — anything larger than a
    handful is worth a closer look.
    """
    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                "SELECT COUNT(*) FROM public.movie_awards "
                "WHERE award_name_entry_id IS NULL"
            )
            row = await cur.fetchone()
    null_count = int(row[0]) if row else 0
    if null_count:
        print(
            f"  Note: {null_count} movie_awards rows still have a NULL "
            "award_name_entry_id (award_name normalized to empty)."
        )
    else:
        print("  All movie_awards rows have a non-NULL award_name_entry_id.")


async def _run_backfill() -> None:
    """
    Main async pass: wipe, populate entries + tokens, stamp movie_awards,
    refresh the DF materialized view.

    Pool lifecycle is owned here — the module-level ``pool`` is created
    with ``open=False`` in db.postgres, so we must open it inside the
    running event loop. Closing in the same loop's ``finally`` prevents
    the "pool bound to a closed loop" RuntimeError a second asyncio.run
    would otherwise hit.
    """
    await pool.open()
    try:
        await _wipe_award_name_data()

        print("Step 3/5: loading distinct award_name values + populating entry/token tables...")
        raw_names = await _load_distinct_award_names()
        raw_to_entry = await _populate_entries_and_tokens(raw_names)

        print("Step 4/5: stamping movie_awards.award_name_entry_id...")
        await _stamp_movie_awards(raw_to_entry)
        await _report_unstamped()

        print("Step 5/5: refreshing lex.award_name_token_doc_frequency...")
        await refresh_award_name_token_doc_frequency()

        print("Backfill complete.")
    finally:
        await pool.close()


def main() -> None:
    _apply_schema_migrations()
    asyncio.run(_run_backfill())


if __name__ == "__main__":
    sys.exit(main())
