"""
One-shot backfill: stamp production-brand and production-company data onto
every movie already present in ``public.movie_card``.

Run once after rebuilding Postgres with the new schema (or after ALTER/CREATE
for a pre-existing database). Safe to re-run: all writes use ON CONFLICT DO
NOTHING or a DELETE+INSERT cycle keyed on movie_id, so iteration is
idempotent.

Pipeline:
  1. ALTER/CREATE — add the movie_card column, GIN index, and the three new
     lex tables (production_company, studio_token, inv_production_brand_postings).
     IF NOT EXISTS throughout; no-op on fresh-init DBs that already got these
     from 01_create_postgres_tables.sql.
  2. Enumerate movies from public.movie_card.
  3. Read each movie's IMDB production_companies list and release_date from
     the ingestion tracker SQLite (./ingestion_data/tracker.db) — same source
     Stage 8 ingestion reads from.
  4. For each movie, call write_production_data — which writes brand
     postings, production_company rows, studio_token rows, and stamps
     production_company_ids onto movie_card.

Why tracker SQLite (not Postgres) for production_companies: movie_card
doesn't persist the raw list — it's consumed only during ingestion. The
tracker is the authoritative source of the IMDB scraped payload on disk.

Batched commits every COMMIT_EVERY movies so a mid-run failure loses at
most one batch.
"""
from __future__ import annotations

import asyncio
import json
import os
import sqlite3
import sys
from pathlib import Path

import psycopg
from dotenv import load_dotenv

from db.postgres import pool, update_movie_card_production_company_ids
from movie_ingestion.final_ingestion.ingest_movie import write_production_data
from movie_ingestion.tracker import TRACKER_DB_PATH

load_dotenv()

# Batch size controls commit granularity. 200 keeps each transaction small
# enough to avoid long idle_in_transaction windows while still amortizing
# round-trip overhead on ~100K movies.
COMMIT_EVERY = 200


def _sync_connect() -> psycopg.Connection:
    """Open a sync psycopg connection for one-off DDL statements."""
    return psycopg.connect(
        host=os.getenv("POSTGRES_HOST"),
        port=int(os.getenv("POSTGRES_PORT", "5432")),
        user=os.getenv("POSTGRES_USER"),
        password=os.getenv("POSTGRES_PASSWORD"),
        dbname=os.getenv("POSTGRES_DB"),
    )


def _apply_schema_migrations() -> None:
    """
    Ensure the new tables, indexes, and movie_card column exist.

    IF NOT EXISTS everywhere so this is a no-op on a database that was
    freshly initialized from 01_create_postgres_tables.sql. All statements
    are safe to run repeatedly.
    """
    with _sync_connect() as conn:
        conn.autocommit = True
        with conn.cursor() as cur:
            print("Step 1/4: applying schema migrations...")

            cur.execute(
                """
                ALTER TABLE public.movie_card
                  ADD COLUMN IF NOT EXISTS production_company_ids BIGINT[] NOT NULL DEFAULT '{}'
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_movie_card_production_company_ids
                  ON public.movie_card USING GIN (production_company_ids)
                """
            )

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS lex.production_company (
                  production_company_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  canonical_string       TEXT NOT NULL,
                  normalized_string      TEXT NOT NULL UNIQUE
                )
                """
            )

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS lex.studio_token (
                  token                  TEXT   NOT NULL,
                  production_company_id  BIGINT NOT NULL REFERENCES lex.production_company ON DELETE CASCADE,
                  PRIMARY KEY (token, production_company_id)
                )
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_studio_token_company
                  ON lex.studio_token (production_company_id)
                """
            )

            cur.execute(
                """
                CREATE TABLE IF NOT EXISTS lex.inv_production_brand_postings (
                  brand_id              SMALLINT NOT NULL,
                  movie_id              BIGINT   NOT NULL,
                  first_matching_index  SMALLINT NOT NULL,
                  total_brand_count     SMALLINT NOT NULL,
                  PRIMARY KEY (brand_id, movie_id)
                )
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_brand_postings_movie
                  ON lex.inv_production_brand_postings (movie_id)
                """
            )


def _load_tracker_rows() -> dict[int, tuple[list[str], int | None]]:
    """
    Read (production_companies, release_year) for every movie in the tracker.

    Returns a ``{tmdb_id: (production_companies, release_year)}`` mapping.
    Missing or malformed JSON is tolerated by treating the list as empty.
    Missing release_date yields release_year=None — the brand resolver drops
    all windowed memberships in that case, per its own documented rule.
    """
    if not Path(TRACKER_DB_PATH).exists():
        raise FileNotFoundError(
            f"Tracker DB not found at {TRACKER_DB_PATH}. "
            "Run ingestion first to populate imdb_data / tmdb_data."
        )

    db = sqlite3.connect(str(TRACKER_DB_PATH))
    db.row_factory = sqlite3.Row
    try:
        # LEFT JOIN — keep movies that have one of the two rows even if the
        # other is missing. In practice both are populated by the time a
        # movie reaches the final ingest, but the backfill shouldn't assume.
        rows = db.execute(
            """
            SELECT i.tmdb_id            AS tmdb_id,
                   i.production_companies AS production_companies,
                   t.release_date       AS release_date
            FROM imdb_data i
            LEFT JOIN tmdb_data t USING (tmdb_id)
            """
        ).fetchall()
    finally:
        db.close()

    out: dict[int, tuple[list[str], int | None]] = {}
    for row in rows:
        tmdb_id = int(row["tmdb_id"])

        # production_companies is a JSON-encoded list of strings in SQLite.
        raw = row["production_companies"]
        companies: list[str] = []
        if raw:
            try:
                decoded = json.loads(raw)
                if isinstance(decoded, list):
                    companies = [str(s) for s in decoded]
            except (ValueError, TypeError):
                companies = []

        # release_date is "YYYY-MM-DD"; take the first four chars. Guard
        # against empty/short values.
        release_year: int | None = None
        date_str = row["release_date"]
        if date_str:
            try:
                release_year = int(str(date_str)[:4])
            except (ValueError, TypeError):
                release_year = None

        out[tmdb_id] = (companies, release_year)
    return out


async def _load_movie_ids_from_card() -> list[int]:
    """Fetch every tmdb_id present in movie_card so we only backfill live rows."""
    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute("SELECT movie_id FROM public.movie_card ORDER BY movie_id")
            rows = await cur.fetchall()
    return [int(row[0]) for row in rows]


async def _run_backfill() -> None:
    """
    Main async pass: iterate movies, run the production data writes + stamp.

    Uses a fresh connection per batch so the idle_in_transaction timeout
    (2 min per 01_create_postgres_tables.sql) can't kill us on large runs.

    Pool lifecycle is owned here — the module-level ``pool`` is created with
    ``open=False`` in db.postgres, so we must open it inside the running
    event loop. Closing inside the same loop's ``finally`` prevents the
    "pool bound to a closed loop" RuntimeError that would otherwise hit if
    we closed via a second ``asyncio.run``.
    """
    await pool.open()
    try:
        print("Step 2/4: loading tracker rows...")
        tracker = _load_tracker_rows()
        print(f"  Loaded {len(tracker):,} imdb_data rows from tracker.")

        print("Step 3/4: loading movie_card ids...")
        movie_ids = await _load_movie_ids_from_card()
        print(f"  Found {len(movie_ids):,} movies in public.movie_card.")

        print(f"Step 4/4: backfilling brand/company data (batches of {COMMIT_EVERY})...")
        total = len(movie_ids)
        processed = 0
        missing_tracker = 0

        # Batch outer loop: one async transaction per COMMIT_EVERY movies.
        for batch_start in range(0, total, COMMIT_EVERY):
            batch = movie_ids[batch_start : batch_start + COMMIT_EVERY]
            async with pool.connection() as conn:
                try:
                    for movie_id in batch:
                        tracker_row = tracker.get(movie_id)
                        if tracker_row is None:
                            # movie_card row with no imdb_data — rare; write
                            # empty production data + stamp empty ids on the
                            # card so a partial state never lingers.
                            missing_tracker += 1
                            company_ids = await write_production_data(
                                movie_id, [], None, conn=conn
                            )
                        else:
                            companies, release_year = tracker_row
                            company_ids = await write_production_data(
                                movie_id, companies, release_year, conn=conn
                            )
                        # Backfill path: movie_card already exists, so we
                        # UPDATE its production_company_ids in place rather
                        # than re-upserting the whole card row.
                        await update_movie_card_production_company_ids(
                            movie_id, company_ids, conn=conn
                        )
                    await conn.commit()
                except Exception as e:
                    await conn.rollback()
                    print(f"  Batch starting at {batch_start} failed: {e}")
                    raise

            processed += len(batch)
            if processed % (COMMIT_EVERY * 10) == 0 or processed == total:
                print(f"  {processed:,} / {total:,} movies backfilled")

        if missing_tracker:
            print(
                f"Note: {missing_tracker} movies had a movie_card row but no "
                "imdb_data in the tracker — written with empty production data."
            )
        print("Backfill complete.")
    finally:
        await pool.close()


def main() -> None:
    _apply_schema_migrations()
    asyncio.run(_run_backfill())


if __name__ == "__main__":
    sys.exit(main())
