-- Postgres bootstrap for movie-finder-rag.
-- This script is executed on first Docker initialization.

-- Required extensions for lexical search behavior and int[] GIN operator class.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS intarray;

-- Auto-kill connections that sit idle in an open transaction for more than 2
-- minutes.  Prevents zombie transactions (e.g. from a crashed ingestion run)
-- from holding row-level locks indefinitely.
ALTER DATABASE moviedb SET idle_in_transaction_session_timeout = '2min';

-- Lexical search schema.
CREATE SCHEMA IF NOT EXISTS lex;

-- Canonical movie metadata used for card rendering, filtering, and reranking.
CREATE TABLE IF NOT EXISTS public.movie_card (
  movie_id            BIGINT PRIMARY KEY,
  title               TEXT NOT NULL,
  poster_url          TEXT,
  release_ts          BIGINT,
  runtime_minutes     INT,
  maturity_rank       SMALLINT,
  genre_ids           INT[] NOT NULL DEFAULT '{}',
  watch_offer_keys    INT[] NOT NULL DEFAULT '{}',
  audio_language_ids  INT[] NOT NULL DEFAULT '{}',
  country_ids         INT[] NOT NULL DEFAULT '{}',
  source_material_type_ids INT[] NOT NULL DEFAULT '{}',
  keyword_ids         INT[] NOT NULL DEFAULT '{}',
  concept_tag_ids     INT[] NOT NULL DEFAULT '{}',
  award_ceremony_win_ids SMALLINT[] NOT NULL DEFAULT '{}',
  imdb_vote_count     INT NOT NULL DEFAULT 0,
  popularity_score    FLOAT NOT NULL DEFAULT 0.0,
  reception_score     FLOAT,
  budget_bucket       TEXT,
  box_office_bucket   TEXT,
  title_token_count   INT NOT NULL DEFAULT 0,
  updated_at          TIMESTAMP NOT NULL DEFAULT now(),
  created_at          TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_movie_card_range
  ON public.movie_card (release_ts, runtime_minutes, maturity_rank);

CREATE INDEX IF NOT EXISTS idx_movie_card_release_ts
  ON public.movie_card (release_ts);

CREATE INDEX IF NOT EXISTS idx_movie_card_runtime_minutes
  ON public.movie_card (runtime_minutes);

CREATE INDEX IF NOT EXISTS idx_movie_card_maturity_rank
  ON public.movie_card (maturity_rank);

-- Explicit gin__int_ops for efficient integer-array overlap filtering (&&).
CREATE INDEX IF NOT EXISTS idx_movie_card_genre_ids
  ON public.movie_card USING GIN (genre_ids gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_watch_offer_keys
  ON public.movie_card USING GIN (watch_offer_keys gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_audio_language_ids
  ON public.movie_card USING GIN (audio_language_ids gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_country_ids
  ON public.movie_card USING GIN (country_ids gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_source_material_type_ids
  ON public.movie_card USING GIN (source_material_type_ids gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_keyword_ids
  ON public.movie_card USING GIN (keyword_ids gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_concept_tag_ids
  ON public.movie_card USING GIN (concept_tag_ids gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_award_ceremony_win_ids
  ON public.movie_card USING GIN (award_ceremony_win_ids);


-- Structured award nominations and wins for deterministic lookup.
-- Queried by ceremony_id + category + outcome_id, optionally filtered by year.
CREATE TABLE IF NOT EXISTS public.movie_awards (
  movie_id      BIGINT NOT NULL REFERENCES public.movie_card ON DELETE CASCADE,
  ceremony_id   SMALLINT NOT NULL,
  category      TEXT,
  outcome_id    SMALLINT NOT NULL,
  year          SMALLINT NOT NULL,
  PRIMARY KEY (movie_id, ceremony_id, COALESCE(category, ''), year)
);

-- Covers: "Oscar winners", "Best Picture nominees", "Cannes winners after 2000"
CREATE INDEX IF NOT EXISTS idx_awards_lookup
  ON public.movie_awards (ceremony_id, category, outcome_id, year);

-- Reverse lookup: given a movie, find all its awards (for display / card rendering)
CREATE INDEX IF NOT EXISTS idx_awards_movie
  ON public.movie_awards (movie_id);

-- Structured franchise metadata for search-time franchise retrieval/filtering.
CREATE TABLE IF NOT EXISTS public.movie_franchise_metadata (
  movie_id               BIGINT PRIMARY KEY REFERENCES public.movie_card ON DELETE CASCADE,
  lineage                TEXT,
  shared_universe        TEXT,
  recognized_subgroups   TEXT[] NOT NULL DEFAULT '{}',
  launched_subgroup      BOOLEAN NOT NULL DEFAULT FALSE,
  lineage_position       SMALLINT,
  is_spinoff             BOOLEAN NOT NULL DEFAULT FALSE,
  is_crossover           BOOLEAN NOT NULL DEFAULT FALSE,
  launched_franchise     BOOLEAN NOT NULL DEFAULT FALSE
);


-- Global dictionary of normalized lexical strings.
CREATE TABLE IF NOT EXISTS lex.lexical_dictionary (
  string_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  norm_str    TEXT NOT NULL UNIQUE,
  created_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- Title-token-only string subset for fuzzy matching scope.
CREATE TABLE IF NOT EXISTS lex.title_token_strings (
  string_id  BIGINT PRIMARY KEY REFERENCES lex.lexical_dictionary(string_id) ON DELETE CASCADE,
  norm_str   TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_title_token_strings_trgm
  ON lex.title_token_strings USING GIN (norm_str gin_trgm_ops);

-- Inverted index postings for title tokens.
CREATE TABLE IF NOT EXISTS lex.inv_title_token_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_title_postings_movie
  ON lex.inv_title_token_postings (movie_id);

-- Inverted index postings for actor names (with billing metadata for prominence scoring).
CREATE TABLE IF NOT EXISTS lex.inv_actor_postings (
  term_id          BIGINT NOT NULL,
  movie_id         BIGINT NOT NULL,
  billing_position INT    NOT NULL,
  cast_size        INT    NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_actor_postings_movie
  ON lex.inv_actor_postings (movie_id);

-- Inverted index postings for director names.
CREATE TABLE IF NOT EXISTS lex.inv_director_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_director_postings_movie
  ON lex.inv_director_postings (movie_id);

-- Inverted index postings for writer names.
CREATE TABLE IF NOT EXISTS lex.inv_writer_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_writer_postings_movie
  ON lex.inv_writer_postings (movie_id);

-- Inverted index postings for producer names.
CREATE TABLE IF NOT EXISTS lex.inv_producer_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_producer_postings_movie
  ON lex.inv_producer_postings (movie_id);

-- Inverted index postings for composer names.
CREATE TABLE IF NOT EXISTS lex.inv_composer_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_composer_postings_movie
  ON lex.inv_composer_postings (movie_id);

-- Character names strings saving
CREATE TABLE IF NOT EXISTS lex.character_strings (
  string_id  BIGINT PRIMARY KEY REFERENCES lex.lexical_dictionary(string_id) ON DELETE CASCADE,
  norm_str   TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_character_strings_trgm
  ON lex.character_strings USING GIN (norm_str gin_trgm_ops);

-- Inverted index postings for character names so we can LIKE match
CREATE TABLE IF NOT EXISTS lex.inv_character_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_character_postings_movie
  ON lex.inv_character_postings (movie_id);

-- Inverted index postings for studio names.
CREATE TABLE IF NOT EXISTS lex.inv_studio_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_studio_postings_movie
  ON lex.inv_studio_postings (movie_id);

-- Inverted index postings for franchise lineage/shared-universe names.
CREATE TABLE IF NOT EXISTS lex.inv_franchise_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_franchise_postings_movie
  ON lex.inv_franchise_postings (movie_id);

-- Materialized view used for max_df stop-word filtering in title matching.
CREATE MATERIALIZED VIEW IF NOT EXISTS lex.title_token_doc_frequency AS
SELECT
  term_id,
  COUNT(*)::BIGINT AS doc_frequency,
  now()            AS updated_at
FROM lex.inv_title_token_postings
GROUP BY term_id;

CREATE UNIQUE INDEX IF NOT EXISTS idx_title_token_df_term_id
  ON lex.title_token_doc_frequency (term_id);
