-- Postgres bootstrap for movie-finder-rag.
-- This script is executed on first Docker initialization.

-- Required extensions for lexical search behavior and int[] GIN operator class.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS intarray;

-- Lexical search schema.
CREATE SCHEMA IF NOT EXISTS lex;

-- Canonical movie metadata used for card rendering, filtering, and reranking.
CREATE TABLE IF NOT EXISTS public.movie_card (
  movie_id            BIGINT PRIMARY KEY,
  title               TEXT NOT NULL,
  poster_url          TEXT,
  release_ts          BIGINT,
  runtime_minutes     INT,
  maturity_rank       SMALLINT,
  genre_ids           INT[] NOT NULL DEFAULT '{}',
  watch_offer_keys    INT[] NOT NULL DEFAULT '{}',
  audio_language_ids  INT[] NOT NULL DEFAULT '{}',
  reception_score     FLOAT,
  title_token_count   INT NOT NULL DEFAULT 0,
  updated_at          TIMESTAMP NOT NULL DEFAULT now(),
  created_at          TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_movie_card_range
  ON public.movie_card (release_ts, runtime_minutes, maturity_rank);

CREATE INDEX IF NOT EXISTS idx_movie_card_release_ts
  ON public.movie_card (release_ts);

CREATE INDEX IF NOT EXISTS idx_movie_card_runtime_minutes
  ON public.movie_card (runtime_minutes);

CREATE INDEX IF NOT EXISTS idx_movie_card_maturity_rank
  ON public.movie_card (maturity_rank);

-- Explicit gin__int_ops for efficient integer-array overlap filtering (&&).
CREATE INDEX IF NOT EXISTS idx_movie_card_genre_ids
  ON public.movie_card USING GIN (genre_ids gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_watch_offer_keys
  ON public.movie_card USING GIN (watch_offer_keys gin__int_ops);

CREATE INDEX IF NOT EXISTS idx_movie_card_audio_language_ids
  ON public.movie_card USING GIN (audio_language_ids gin__int_ops);



-- Global dictionary of normalized lexical strings.
CREATE TABLE IF NOT EXISTS lex.lexical_dictionary (
  string_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  norm_str    TEXT NOT NULL UNIQUE,
  created_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- Title-token-only string subset for fuzzy matching scope.
CREATE TABLE IF NOT EXISTS lex.title_token_strings (
  string_id  BIGINT PRIMARY KEY REFERENCES lex.lexical_dictionary(string_id) ON DELETE CASCADE,
  norm_str   TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_title_token_strings_trgm
  ON lex.title_token_strings USING GIN (norm_str gin_trgm_ops);

-- Inverted index postings for title tokens.
CREATE TABLE IF NOT EXISTS lex.inv_title_token_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_title_postings_movie
  ON lex.inv_title_token_postings (movie_id);

-- Inverted index postings for people names.
CREATE TABLE IF NOT EXISTS lex.inv_person_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_person_postings_movie
  ON lex.inv_person_postings (movie_id);

-- Character names strings saving
CREATE TABLE IF NOT EXISTS lex.character_strings (
  string_id  BIGINT PRIMARY KEY REFERENCES lex.lexical_dictionary(string_id) ON DELETE CASCADE,
  norm_str   TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_character_strings_trgm
  ON lex.character_strings USING GIN (norm_str gin_trgm_ops);

-- Inverted index postings for character names so we can LIKE match
CREATE TABLE IF NOT EXISTS lex.inv_character_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_character_postings_movie
  ON lex.inv_character_postings (movie_id);

-- Inverted index postings for studio names.
CREATE TABLE IF NOT EXISTS lex.inv_studio_postings (
  term_id   BIGINT NOT NULL,
  movie_id  BIGINT NOT NULL,
  PRIMARY KEY (term_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_studio_postings_movie
  ON lex.inv_studio_postings (movie_id);

-- Optional lookup tables for introspection and admin tooling.
CREATE TABLE IF NOT EXISTS lex.genre_dictionary (
  genre_id  INT PRIMARY KEY,
  name      TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS lex.language_dictionary (
  language_id  INT PRIMARY KEY,
  name         TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS lex.provider_dictionary (
  provider_id  INT PRIMARY KEY,
  name         TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS lex.watch_method_dictionary (
  method_id  INT PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS lex.maturity_dictionary (
  maturity_rank  SMALLINT PRIMARY KEY,
  label          TEXT NOT NULL UNIQUE
);

-- Materialized view used for max_df stop-word filtering in title matching.
CREATE MATERIALIZED VIEW IF NOT EXISTS lex.title_token_doc_frequency AS
SELECT
  term_id,
  COUNT(*)::BIGINT AS doc_frequency,
  now()            AS updated_at
FROM lex.inv_title_token_postings
GROUP BY term_id;

CREATE UNIQUE INDEX IF NOT EXISTS idx_title_token_df_term_id
  ON lex.title_token_doc_frequency (term_id);
