"""Country enum for movie production/release countries."""

from enum import Enum
from implementation.misc.helpers import normalize_string


class Country(Enum):
    """Enum of IMDB-supported countries and territories with stable numeric IDs.

    Includes current sovereign states, dependent territories, and historical
    entities retained for cataloging older films.
    """

    country_id: int
    value: str

    def __new__(cls, country_id: int, value: str) -> "Country":
        """Create a Country enum member with an ID and display value."""
        obj = object.__new__(cls)
        obj._value_ = value
        obj.country_id = country_id
        return obj

    # Current countries and territories
    ANDORRA = (1, "Andorra")
    UNITED_ARAB_EMIRATES = (2, "United Arab Emirates")
    AFGHANISTAN = (3, "Afghanistan")
    ANTIGUA_AND_BARBUDA = (4, "Antigua & Barbuda")
    ANGUILLA = (5, "Anguilla")
    ALBANIA = (6, "Albania")
    ARMENIA = (7, "Armenia")
    NETHERLANDS_ANTILLES = (8, "Netherlands Antilles")
    ANGOLA = (9, "Angola")
    ANTARCTICA = (10, "Antarctica")
    ARGENTINA = (11, "Argentina")
    AMERICAN_SAMOA = (12, "American Samoa")
    AUSTRIA = (13, "Austria")
    AUSTRALIA = (14, "Australia")
    ARUBA = (15, "Aruba")
    ALAND_ISLANDS = (16, "Åland Islands")
    AZERBAIJAN = (17, "Azerbaijan")
    BOSNIA_AND_HERZEGOVINA = (18, "Bosnia & Herzegovina")
    BARBADOS = (19, "Barbados")
    BANGLADESH = (20, "Bangladesh")
    BELGIUM = (21, "Belgium")
    BURKINA_FASO = (22, "Burkina Faso")
    BULGARIA = (23, "Bulgaria")
    BAHRAIN = (24, "Bahrain")
    BURUNDI = (25, "Burundi")
    BENIN = (26, "Benin")
    ST_BARTHELEMY = (27, "St. Barthélemy")
    BERMUDA = (28, "Bermuda")
    BRUNEI = (29, "Brunei")
    BOLIVIA = (30, "Bolivia")
    CARIBBEAN_NETHERLANDS = (31, "Caribbean Netherlands")
    BRAZIL = (32, "Brazil")
    BAHAMAS = (33, "Bahamas")
    BHUTAN = (34, "Bhutan")
    BOUVET_ISLAND = (35, "Bouvet Island")
    BOTSWANA = (36, "Botswana")
    BELARUS = (37, "Belarus")
    BELIZE = (38, "Belize")
    CANADA = (39, "Canada")
    COCOS_KEELING_ISLANDS = (40, "Cocos (Keeling) Islands")
    CONGO_KINSHASA = (41, "Congo - Kinshasa")
    CENTRAL_AFRICAN_REPUBLIC = (42, "Central African Republic")
    CONGO_BRAZZAVILLE = (43, "Congo - Brazzaville")
    SWITZERLAND = (44, "Switzerland")
    COTE_DIVOIRE = (45, "Côte d'Ivoire")
    COOK_ISLANDS = (46, "Cook Islands")
    CHILE = (47, "Chile")
    CAMEROON = (48, "Cameroon")
    CHINA = (49, "China")
    COLOMBIA = (50, "Colombia")
    COSTA_RICA = (51, "Costa Rica")
    CUBA = (52, "Cuba")
    CAPE_VERDE = (53, "Cape Verde")
    CURACAO = (54, "Curaçao")
    CHRISTMAS_ISLAND = (55, "Christmas Island")
    CYPRUS = (56, "Cyprus")
    CZECHIA = (57, "Czechia")
    GERMANY = (58, "Germany")
    DJIBOUTI = (59, "Djibouti")
    DENMARK = (60, "Denmark")
    DOMINICA = (61, "Dominica")
    DOMINICAN_REPUBLIC = (62, "Dominican Republic")
    ALGERIA = (63, "Algeria")
    ECUADOR = (64, "Ecuador")
    ESTONIA = (65, "Estonia")
    EGYPT = (66, "Egypt")
    WESTERN_SAHARA = (67, "Western Sahara")
    ERITREA = (68, "Eritrea")
    SPAIN = (69, "Spain")
    ETHIOPIA = (70, "Ethiopia")
    FINLAND = (71, "Finland")
    FIJI = (72, "Fiji")
    FALKLAND_ISLANDS = (73, "Falkland Islands")
    MICRONESIA = (74, "Micronesia")
    FAROE_ISLANDS = (75, "Faroe Islands")
    FRANCE = (76, "France")
    GABON = (77, "Gabon")
    UNITED_KINGDOM = (78, "United Kingdom")
    GRENADA = (79, "Grenada")
    GEORGIA = (80, "Georgia")
    FRENCH_GUIANA = (81, "French Guiana")
    GUERNSEY = (82, "Guernsey")
    GHANA = (83, "Ghana")
    GIBRALTAR = (84, "Gibraltar")
    GREENLAND = (85, "Greenland")
    GAMBIA = (86, "Gambia")
    GUINEA = (87, "Guinea")
    GUADELOUPE = (88, "Guadeloupe")
    EQUATORIAL_GUINEA = (89, "Equatorial Guinea")
    GREECE = (90, "Greece")
    SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS = (91, "South Georgia & South Sandwich Islands")
    GUATEMALA = (92, "Guatemala")
    GUAM = (93, "Guam")
    GUINEA_BISSAU = (94, "Guinea-Bissau")
    GUYANA = (95, "Guyana")
    HONG_KONG = (96, "Hong Kong SAR China")
    HEARD_AND_MCDONALD_ISLANDS = (97, "Heard & McDonald Islands")
    HONDURAS = (98, "Honduras")
    CROATIA = (99, "Croatia")
    HAITI = (100, "Haiti")
    HUNGARY = (101, "Hungary")
    INDONESIA = (102, "Indonesia")
    IRELAND = (103, "Ireland")
    ISRAEL = (104, "Israel")
    ISLE_OF_MAN = (105, "Isle of Man")
    INDIA = (106, "India")
    BRITISH_INDIAN_OCEAN_TERRITORY = (107, "British Indian Ocean Territory")
    IRAQ = (108, "Iraq")
    IRAN = (109, "Iran")
    ICELAND = (110, "Iceland")
    ITALY = (111, "Italy")
    JERSEY = (112, "Jersey")
    JAMAICA = (113, "Jamaica")
    JORDAN = (114, "Jordan")
    JAPAN = (115, "Japan")
    KENYA = (116, "Kenya")
    KYRGYZSTAN = (117, "Kyrgyzstan")
    CAMBODIA = (118, "Cambodia")
    KIRIBATI = (119, "Kiribati")
    COMOROS = (120, "Comoros")
    ST_KITTS_AND_NEVIS = (121, "St. Kitts & Nevis")
    NORTH_KOREA = (122, "North Korea")
    SOUTH_KOREA = (123, "South Korea")
    KUWAIT = (124, "Kuwait")
    CAYMAN_ISLANDS = (125, "Cayman Islands")
    KAZAKHSTAN = (126, "Kazakhstan")
    LAOS = (127, "Laos")
    LEBANON = (128, "Lebanon")
    ST_LUCIA = (129, "St. Lucia")
    LIECHTENSTEIN = (130, "Liechtenstein")
    SRI_LANKA = (131, "Sri Lanka")
    LIBERIA = (132, "Liberia")
    LESOTHO = (133, "Lesotho")
    LITHUANIA = (134, "Lithuania")
    LUXEMBOURG = (135, "Luxembourg")
    LATVIA = (136, "Latvia")
    LIBYA = (137, "Libya")
    MOROCCO = (138, "Morocco")
    MONACO = (139, "Monaco")
    MOLDOVA = (140, "Moldova")
    MONTENEGRO = (141, "Montenegro")
    ST_MARTIN = (142, "St. Martin")
    MADAGASCAR = (143, "Madagascar")
    MARSHALL_ISLANDS = (144, "Marshall Islands")
    NORTH_MACEDONIA = (145, "North Macedonia")
    MALI = (146, "Mali")
    MYANMAR = (147, "Myanmar (Burma)")
    MONGOLIA = (148, "Mongolia")
    MACAO = (149, "Macao SAR China")
    NORTHERN_MARIANA_ISLANDS = (150, "Northern Mariana Islands")
    MARTINIQUE = (151, "Martinique")
    MAURITANIA = (152, "Mauritania")
    MONTSERRAT = (153, "Montserrat")
    MALTA = (154, "Malta")
    MAURITIUS = (155, "Mauritius")
    MALDIVES = (156, "Maldives")
    MALAWI = (157, "Malawi")
    MEXICO = (158, "Mexico")
    MALAYSIA = (159, "Malaysia")
    MOZAMBIQUE = (160, "Mozambique")
    NAMIBIA = (161, "Namibia")
    NEW_CALEDONIA = (162, "New Caledonia")
    NIGER = (163, "Niger")
    NORFOLK_ISLAND = (164, "Norfolk Island")
    NIGERIA = (165, "Nigeria")
    NICARAGUA = (166, "Nicaragua")
    NETHERLANDS = (167, "Netherlands")
    NORWAY = (168, "Norway")
    NEPAL = (169, "Nepal")
    NAURU = (170, "Nauru")
    NIUE = (171, "Niue")
    NEW_ZEALAND = (172, "New Zealand")
    OMAN = (173, "Oman")
    PANAMA = (174, "Panama")
    PERU = (175, "Peru")
    FRENCH_POLYNESIA = (176, "French Polynesia")
    PAPUA_NEW_GUINEA = (177, "Papua New Guinea")
    PHILIPPINES = (178, "Philippines")
    PAKISTAN = (179, "Pakistan")
    POLAND = (180, "Poland")
    ST_PIERRE_AND_MIQUELON = (181, "St. Pierre & Miquelon")
    PITCAIRN_ISLANDS = (182, "Pitcairn Islands")
    PUERTO_RICO = (183, "Puerto Rico")
    PALESTINIAN_TERRITORIES = (184, "Palestinian Territories")
    PORTUGAL = (185, "Portugal")
    PALAU = (186, "Palau")
    PARAGUAY = (187, "Paraguay")
    QATAR = (188, "Qatar")
    REUNION = (189, "Réunion")
    ROMANIA = (190, "Romania")
    SERBIA = (191, "Serbia")
    RUSSIA = (192, "Russia")
    RWANDA = (193, "Rwanda")
    SAUDI_ARABIA = (194, "Saudi Arabia")
    SOLOMON_ISLANDS = (195, "Solomon Islands")
    SEYCHELLES = (196, "Seychelles")
    SUDAN = (197, "Sudan")
    SWEDEN = (198, "Sweden")
    SINGAPORE = (199, "Singapore")
    ST_HELENA = (200, "St. Helena")
    SLOVENIA = (201, "Slovenia")
    SVALBARD_AND_JAN_MAYEN = (202, "Svalbard & Jan Mayen")
    SLOVAKIA = (203, "Slovakia")
    SIERRA_LEONE = (204, "Sierra Leone")
    SAN_MARINO = (205, "San Marino")
    SENEGAL = (206, "Senegal")
    SOMALIA = (207, "Somalia")
    SURINAME = (208, "Suriname")
    SAO_TOME_AND_PRINCIPE = (209, "São Tomé & Príncipe")
    EL_SALVADOR = (210, "El Salvador")
    SYRIA = (211, "Syria")
    ESWATINI = (212, "Eswatini")
    TURKS_AND_CAICOS_ISLANDS = (213, "Turks & Caicos Islands")
    CHAD = (214, "Chad")
    FRENCH_SOUTHERN_TERRITORIES = (215, "French Southern Territories")
    TOGO = (216, "Togo")
    THAILAND = (217, "Thailand")
    TAJIKISTAN = (218, "Tajikistan")
    TOKELAU = (219, "Tokelau")
    TIMOR_LESTE = (220, "Timor-Leste")
    TURKMENISTAN = (221, "Turkmenistan")
    TUNISIA = (222, "Tunisia")
    TONGA = (223, "Tonga")
    TURKEY = (224, "Turkey")
    TRINIDAD_AND_TOBAGO = (225, "Trinidad & Tobago")
    TUVALU = (226, "Tuvalu")
    TAIWAN = (227, "Taiwan")
    TANZANIA = (228, "Tanzania")
    UKRAINE = (229, "Ukraine")
    UGANDA = (230, "Uganda")
    US_OUTLYING_ISLANDS = (231, "U.S. Outlying Islands")
    UNITED_STATES = (232, "United States")
    URUGUAY = (233, "Uruguay")
    UZBEKISTAN = (234, "Uzbekistan")
    VATICAN_CITY = (235, "Vatican City")
    ST_VINCENT_AND_GRENADINES = (236, "St. Vincent & Grenadines")
    VENEZUELA = (237, "Venezuela")
    BRITISH_VIRGIN_ISLANDS = (238, "British Virgin Islands")
    US_VIRGIN_ISLANDS = (239, "U.S. Virgin Islands")
    VIETNAM = (240, "Vietnam")
    VANUATU = (241, "Vanuatu")
    WALLIS_AND_FUTUNA = (242, "Wallis & Futuna")
    SAMOA = (243, "Samoa")
    KOSOVO = (244, "Kosovo")
    PALESTINE = (245, "Palestine")
    YEMEN = (246, "Yemen")
    MAYOTTE = (247, "Mayotte")
    SOUTH_AFRICA = (248, "South Africa")
    ZAMBIA = (249, "Zambia")
    ZIMBABWE = (250, "Zimbabwe")

    # Historical entities (no longer exist, retained for older films)
    BURMA = (251, "Burma")
    CZECHOSLOVAKIA = (252, "Czechoslovakia")
    SERBIA_AND_MONTENEGRO = (253, "Serbia and Montenegro")
    EAST_GERMANY = (254, "East Germany")
    SOVIET_UNION = (255, "Soviet Union")
    NORTH_VIETNAM = (256, "North Vietnam")
    KOREA = (257, "Korea")
    SIAM = (258, "Siam")
    WEST_GERMANY = (259, "West Germany")
    YUGOSLAVIA = (260, "Yugoslavia")
    FEDERAL_REPUBLIC_OF_YUGOSLAVIA = (261, "Federal Republic of Yugoslavia")
    ZAIRE = (262, "Zaire")

_COUNTRY_ALIASES: dict[str, Country] = {
    "Antigua and Barbuda": Country.ANTIGUA_AND_BARBUDA,
    "Bosnia and Herzegovina": Country.BOSNIA_AND_HERZEGOVINA,
    "Cocos Islands": Country.COCOS_KEELING_ISLANDS,
    "Congo": Country.CONGO_BRAZZAVILLE,
    "Czech Republic": Country.CZECHIA,
    "Hong Kong": Country.HONG_KONG,
    "Macao": Country.MACAO,
    "Myanmar": Country.MYANMAR,
    "Occupied Palestinian Territory": Country.PALESTINIAN_TERRITORIES,
    "Saint Helena": Country.ST_HELENA,
    "Saint Kitts and Nevis": Country.ST_KITTS_AND_NEVIS,
    "Saint Lucia": Country.ST_LUCIA,
    "Saint Vincent and the Grenadines": Country.ST_VINCENT_AND_GRENADINES,
    "Sao Tome and Principe": Country.SAO_TOME_AND_PRINCIPE,
    "South Georgia and the South Sandwich Islands": Country.SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS,
    "Svalbard and Jan Mayen": Country.SVALBARD_AND_JAN_MAYEN,
    "Swaziland": Country.ESWATINI,
    "The Democratic Republic of Congo": Country.CONGO_KINSHASA,
    "Trinidad and Tobago": Country.TRINIDAD_AND_TOBAGO,
    "Turks and Caicos Islands": Country.TURKS_AND_CAICOS_ISLANDS,
    "Vatican": Country.VATICAN_CITY,
}

COUNTRY_BY_NORMALIZED_NAME: dict[str, Country] = {
    normalize_string(name): country
    for name, country in (
        [(country.value, country) for country in Country]
        + list(_COUNTRY_ALIASES.items())
    )
}


def country_from_string(raw_country: str) -> Country | None:
    """Resolve a raw country string to the canonical Country enum."""
    normalized = normalize_string(raw_country)
    if not normalized:
        return None
    return COUNTRY_BY_NORMALIZED_NAME.get(normalized)
