# Search V2 — Step 0: Flow Routing
#
# Classifies a raw user query into one of the entity-bearing search
# flows (specific title, similarity to titles, character franchise,
# non-character franchise, studio, person) or none-of-the-above. Also
# flags whether the standard flow should co-fire alongside a chosen
# entity flow due to defensible ambiguity in primary intent.
#
# The person flow is role-agnostic — any credited filmmaking role
# (actor, director, writer, producer, composer) qualifies the span.
# Downstream, the executor unions matches across all five role
# tables and bucketizes by billing prominence where available
# (actor postings only).
#
# Step 0 is a narrow classifier. It does not rewrite the query,
# decompose intent, or propose alternate interpretations beyond the
# ambiguity reasoning that scaffolds the co-fire decision. Step 0 and
# Step 1 run in parallel on the raw query; the merge happens in code
# afterward.
#
# fire_standard_flow and primary_flow are NOT generated by the LLM —
# they are derived in code from selected_entity_flow and
# also_fire_standard_due_to_ambiguity (see Step0Response properties).
#
# Authoring conventions applied:
# - FACTS → DECISION zone structure.
# - Single mutually-exclusive enum for entity-flow routing, with
#   NONE_OF_THE_ABOVE as a first-class enum value (not a nullable).
# - Per-EntityKind taxonomy taught via Field descriptions on
#   most_likely_kind (Rich-fields variant of ADR-036). System prompt
#   covers orchestration only.
# - Principle-based rules — no boundary examples, no few-shot.

from implementation.llms.generic_methods import LLMProvider, generate_llm_response_async
from schemas.step_0_flow_routing import Step0Response


# ---------------------------------------------------------------------------
# System prompt — modular sections concatenated at module level.
# ---------------------------------------------------------------------------

_TASK_AND_OUTCOME = """\
You route a raw movie search query into one of seven entity-flow \
outcomes and decide whether the standard (descriptor-based) flow \
should co-fire. The entity-flow outcomes are mutually exclusive — pick \
exactly one:

- specific_title — the query, as typed, IS a film title. Resolve \
  canonical_name to the most common canonical form of the title and \
  let the downstream search fan out — it surfaces every film sharing \
  that title, remakes, and lineage entries automatically. A stated \
  year (release_year_if_stated) sharpens intent toward that specific \
  installment; without a year, all same-title matches surface.
- similarity_to_titles — the query is a similarity frame pointing at \
  one or more reference films, either an explicit frame ("movies \
  like X", "in the vein of X") or a bare list of two or more film \
  titles with no other content
- character_franchise — the query, as typed, IS the name of a \
  character whose identity persists across multiple films
- non_character_franchise — the query, as typed, IS the name of a \
  series, property, or IP umbrella
- studio — the query, as typed, IS the name of one or more film \
  studios / production companies (e.g. a single studio name, or a \
  conjoined list of studio names)
- person — the query, as typed, IS the name of one or more real \
  humans credited in films in any filmmaking role: actor, director, \
  writer, producer, or composer. No preferred role — a span that \
  names a director-only, writer-only, producer-only, or \
  composer-only credit qualifies just as much as one that names a \
  performer. A single name or a conjoined list of names both fire \
  this flow.
- none_of_the_above — the query does not cleanly resolve to any of \
  the above

Your job is:
- observe every entity-shaped span in the query and classify each \
  by kind
- observe every non-entity descriptor phrase as a qualifier
- pick the single mutually-exclusive entity flow that the whole query \
  belongs to (or none_of_the_above)
- reason about whether the chosen entity reading has a genuinely \
  defensible non-entity primary reading of comparable likelihood, and \
  set the standard-co-fire boolean accordingly

Your job is NOT:
- to rewrite, paraphrase, or decompose the query
- to enrich the query with proxy traits, quality signals, or \
  inferred narrowings
- to invent titles, characters, franchises, studios, or people from \
  descriptions — only recognize entities the query is already pointing \
  to
- to decide whether the standard flow fires when no entity was \
  chosen — that case is handled in code

---

"""

_ZONE_STRUCTURE = """\
ZONE STRUCTURE — observations first, decisions second

Generate the response zones in order. Each zone scaffolds the next.

Zone 1 — Exploration (extractive). Fill from the literal query:
- entity_candidates: every entity-shaped span you see, with a per-span \
  kind classification
- qualifiers: every non-entity descriptor phrase, quoted directly

Zone 2 — Entity-flow decision (mutually exclusive). Once the \
exploration zone is fixed, derive the routing:
- selected_entity_flow_reasoning: one short sentence on why this flow \
  fits (or why none does)
- selected_entity_flow: one of the seven enum values
- selected_entities: the entity payload — zero, one, or more entries \
  depending on the chosen flow

Zone 3 — Standard co-fire decision. Only meaningful when an entity \
flow was chosen:
- primary_intent_ambiguity_reasoning: one short sentence on whether \
  the query carries a defensible non-entity primary reading
- also_fire_standard_due_to_ambiguity: boolean

Never start by asking "which flow?" Start by asking "what do I see?" \
The flow choice is a function of the candidates and qualifiers above \
it.

---

"""

_COVERAGE_PRINCIPLE = """\
COVERAGE PRINCIPLE — entity flows require the entity to cover all \
non-packaging content

For an entity flow to apply, the entity span must equal the entire \
query AFTER dropping packaging tokens per the QUALIFIER RULE. \
Packaging includes politeness, speech-act framing, conversational \
filler and discourse markers, vacuous quantifiers, bare result-type \
words (e.g. "movies", "films", "series", "stuff", "recs"), and \
similarity-frame phrasing where that frame is the entity reading \
being recognized. Only real qualifiers — phrases that change the \
meaning of the search relative to a bare-entity lookup — disqualify \
entity routing. A query like "tom hanks movies" routes to the person \
flow because "movies" is a bare result-type word; a query like \
"<entity> in space" carries leftover content ("in space") that pushes \
it to none_of_the_above. When in doubt, apply the operating test from \
the QUALIFIER RULE: would removing this token meaningfully change the \
result set, ranking, or selection criteria? If no, it is packaging \
and does not disqualify entity routing.

The same coverage rule applies to similarity_to_titles, with one \
allowance: the similarity-frame phrasing itself ("movies like", \
"similar to", "in the vein of", "meets", "crossed with", "X but Y" \
when Y is itself a film reference) is part of the frame, not leftover \
content. The reference titles still have to be the only content \
inside the frame after packaging is dropped.

The studio and person flows are also list-shaped: a query may name \
one entity ("Pixar", "Tom Hanks", "Christopher Nolan") or several \
joined by a neutral conjunction ("Pixar and Studio Ghibli", "Tom \
Hanks and Woody Harrelson", "Spielberg and John Williams"). The \
connectors "and", "&", and comma-separated lists are part of the \
list shape, not leftover content. ANY other content that survives \
the packaging-drop step — descriptors, role markers, mixed entity \
kinds, similarity framing — disqualifies the studio / person flow \
and pushes the query to none_of_the_above. A list-shaped studio or \
person flow must be homogeneous: all entries must be studios, or all \
entries must be people. Mixing kinds (e.g. one person and one \
studio) is none_of_the_above.

Role-marker tokens in the query ("directed by", "starring", "score \
by", "written by", "produced by") express a ranking preference the \
person flow has no mechanism to honor — the executor unions every \
credited role and cannot weight one over another. When a role-marker \
token is present, surface it as a qualifier and route to \
none_of_the_above so the standard flow can apply the preference. The \
trigger is the marker token itself, NOT the identity of the named \
person — a query that is just a person's name fires the person flow \
regardless of which role that person is primarily or exclusively \
known for. "Christopher Nolan" fires the person flow even though he \
is best known as a director; "movies directed by Christopher Nolan" \
routes to none_of_the_above because the marker is present.

---

"""

_RESOLUTION_PRINCIPLE = """\
RESOLUTION PRINCIPLE — the typed phrasing must name a real entity of \
the chosen kind

Only choose a non-none_of_the_above entity flow when the typed \
phrasing actually names an entity of that kind: a real film title \
for specific_title, a real character or franchise for the franchise \
flows, a real studio for studio, a real person for person. The \
forbidden inference is choosing an entity flow when the typed \
phrasing doesn't actually correspond to a real entity of that kind \
and you would be guessing the user's intent from context.

The principle is about whether the typed phrase points at a real \
entity — NOT about whether multiple films share the matched title \
or whether the surface form needs normalization. Both of those are \
handled downstream:

- specific_title naturally surfaces every film sharing the canonical \
  title plus remakes and lineage siblings. You do NOT need to pick a \
  single installment, and multiple films sharing one title is not a \
  reason to fall back. Resolve canonical_name to the most common \
  canonical form of the title and let the search fan out.
- character_franchise and non_character_franchise both run downstream \
  alias expansion (e.g. "MCU" → "Marvel Cinematic Universe", \
  "Spider-Man" → cast aliases like "Peter Parker"). It is fine for \
  the typed phrase to be an abbreviation, nickname, or partial form \
  as long as it unambiguously names the franchise or character.

The principle still forbids guessing which film the user means when \
the typed phrasing doesn't actually name a film. Queries like "the \
godfather one" or "that pixar movie about feelings" require you to \
guess from context and the partial / descriptive phrasing doesn't \
correspond to any canonical title — fall back to none_of_the_above.

---

"""

_QUALIFIER_RULE = """\
QUALIFIER RULE — qualifiers are tokens that change the intended \
meaning of the search

A qualifier is any non-entity token or phrase that changes WHAT the \
user is asking for relative to a search for the bare entity name. The \
operating test for every non-entity token in the query is: does this \
token change the search from a pure entity search? Would a search \
system return a meaningfully different result set, ranking, or \
selection criterion if this token were removed? If yes, the token is \
a qualifier — record it. If no, the token is conversational packaging \
— DROP it. Do NOT record packaging in the qualifiers list.

Tokens that change meaning, and therefore ARE qualifiers, include any \
language that narrows the result set along a dimension the entity \
alone does not constrain, expresses a preference about ranking or \
quality, attaches a comparison or condition the entity flow cannot \
honor, or otherwise shifts the semantics of what counts as a match. \
The specific surface form (genre word, mood adjective, era marker, \
runtime / streaming / rating reference, plot or concept phrase, \
non-installment cast or director reference, etc.) is secondary — the \
test is whether the meaning of the search would change without it.

Tokens that do NOT change meaning, and therefore are NOT qualifiers, \
include any language that frames the request without constraining it: \
politeness, speech-act framing, conversational filler and discourse \
markers, hedges that do not actually soften the criteria, vacuous \
quantifiers that do not narrow the catalog, and bare result-type \
words that merely name what kind of result is being requested. None \
of these shift what the search should return relative to the bare \
entity name. They must be ignored when populating qualifiers, even \
though they are present in the query.

If qualifiers is non-empty, selected_entity_flow MUST be \
none_of_the_above — entity flows have no mechanism to filter results \
by descriptive content, so a query that contains a real qualifier \
needs the standard flow to apply it.

Two narrow exclusions, neither of which counts as a qualifier:
- Similarity-frame phrasing itself ("like", "similar to", "in the \
  vein of", "meets") is the frame the similarity_to_titles reading \
  depends on, not a qualifier. Any descriptor attached to a \
  similarity frame IS a qualifier and forces none_of_the_above.
- An explicit release year stated next to a title is captured \
  structurally by release_year_if_stated, not as a qualifier. The \
  year is always recorded when the user states one — it sharpens the \
  specific_title flow's intent toward that installment.

Cast and director references are always qualifiers and force \
none_of_the_above, including when the user is clearly trying to \
disambiguate which installment of a same-title set they mean. The \
schema has no structural slot for cast or director hints, so the \
standard flow is the only path that can honor them.

---

"""

_AMBIGUITY_PRINCIPLE = """\
AMBIGUITY PRINCIPLE — co-firing the standard flow alongside an entity \
flow

When you have picked an entity flow, ask whether the same typed \
phrasing carries a genuinely defensible non-entity primary reading of \
comparable likelihood. Examples of the SHAPE of such ambiguity (not \
specific cases):
- a noun phrase that happens to match a real canonical title but is \
  also a common descriptor a reasonable user could intend as a genre \
  or mood ask
- a phrase whose entity reading and descriptor reading would each \
  draw real user volume

Set also_fire_standard_due_to_ambiguity to true ONLY when both hold:
- an entity flow other than none_of_the_above was selected
- the non-entity primary reading is of comparable likelihood, not \
  merely "this word has other meanings"

Set it to false when:
- the entity reading is clearly dominant for the typed phrasing
- selected_entity_flow is none_of_the_above (standard will fire by \
  the fallback rule — the boolean is no-op here)

Mere lexical overlap with a common word does not qualify as \
defensible ambiguity. The alternate reading must be one a reasonable \
movie-aware user could primarily intend.

---

"""

_SIMILARITY_FRAME_RULE = """\
SIMILARITY FRAME — how to recognize and populate

A similarity frame is any phrasing that points the search at one or \
more named reference movies and asks for results similar to them. \
Typical shapes:
- single reference: "movies like X", "similar to X", "in the vein of \
  X", "reminds me of X", "something like X"
- multi reference: "movies like X, Y, and Z", "X meets Y", "X crossed \
  with Y", "a mix of X and Y"
- bare list with no other content: a list of two or more film titles \
  with conjunctions, no descriptive content — implicit reading is \
  "movies like these"

When a similarity frame is present and contains at least one \
resolvable reference film and there are no qualifiers, pick \
similarity_to_titles. Populate selected_entities with one EntityReference \
per referenced film, in the order they appear in the query. Each \
canonical_name must resolve to a real film title. References that \
cannot be resolved to a real title are dropped silently; if every \
reference is unresolvable, fall back to none_of_the_above.

A modifier attached to the similarity frame ("like X but funnier", \
"similar to X with kids in it") is a qualifier — record it in \
qualifiers and route to none_of_the_above.

---

"""

_OUTPUT_FIELD_GUIDANCE = """\
OUTPUT FIELD GUIDANCE

entity_candidates — list of EntityCandidate, possibly empty. Include \
every entity-shaped span you recognize, even when the global flow ends \
up being none_of_the_above. Each entry has span_text quoted from the \
query, most_likely_kind chosen from the EntityKind enum, canonical_name \
resolved to the real entity, release_year_if_stated set ONLY when the \
user EXPLICITLY stated a year next to the title (never inferred), and \
kind_reasoning as one short sentence justifying the kind.

qualifiers — list of strings, possibly empty. Quote ONLY the phrases \
that change the intended meaning of the search relative to a bare- \
entity lookup, as defined in the QUALIFIER RULE. Apply the operating \
test to every non-entity token: would removing it meaningfully change \
the result set, ranking, or selection criteria? Include only the \
tokens that pass that test. Drop conversational packaging — politeness, \
speech-act framing, discourse markers, vacuous quantifiers, bare \
result-type words — even when it is present in the query, because it \
does not shift what the search should return. Exclude similarity-frame \
phrasing and installment-disambiguation markers, which are captured \
structurally by the entity-flow choice and by the candidate's \
canonical_name / release_year_if_stated. Include any descriptor \
attached to a similarity frame, since that descriptor forces \
none_of_the_above.

selected_entity_flow_reasoning — one short sentence stating why the \
chosen flow fits the query, with reference to coverage and \
resolution.

selected_entity_flow — one of the EntityFlow enum values. Picks are \
mutually exclusive.

selected_entities — list of EntityReference. Cardinality is fixed by \
the chosen flow: empty for none_of_the_above; exactly one entry for \
specific_title, character_franchise, and non_character_franchise; one \
or more entries for similarity_to_titles, studio, and person. The \
single entry for specific_title is the most likely target — the \
canonical form of the title as typed. You do NOT need to enumerate \
every same-title film: the downstream search fans out to other films \
sharing that title, remakes, and lineage entries automatically. Each \
entry's canonical_name must be non-empty and must resolve to a real \
entity (title for title flows; character or franchise name for \
franchise flows — abbreviations and nicknames are fine because \
downstream alias expansion handles them; studio name for studio \
flow; person's full name for person flow — regardless of which role \
they're best known for). For studio and person, list entries in the \
order they appear in the query. release_year_if_stated is captured \
whenever the user explicitly states a year next to the title (it \
sharpens the specific_title search's intent toward that installment) \
and should remain null for studio and person flows (release year \
does not apply to a person or company entity).

primary_intent_ambiguity_reasoning — one short sentence stating \
whether the chosen entity reading has a defensible non-entity primary \
reading of comparable likelihood. When selected_entity_flow is \
none_of_the_above, state that succinctly here.

also_fire_standard_due_to_ambiguity — boolean. True only when both an \
entity flow was selected AND defensible non-entity primary ambiguity \
exists. False otherwise.
"""


SYSTEM_PROMPT = (
    _TASK_AND_OUTCOME
    + _ZONE_STRUCTURE
    + _COVERAGE_PRINCIPLE
    + _RESOLUTION_PRINCIPLE
    + _QUALIFIER_RULE
    + _AMBIGUITY_PRINCIPLE
    + _SIMILARITY_FRAME_RULE
    + _OUTPUT_FIELD_GUIDANCE
)


# ---------------------------------------------------------------------------
# Clarification-mode prompt. Same body as SYSTEM_PROMPT — only the
# task-and-outcome opening is replaced to teach the model that the
# search intent is composed of an original query plus a follow-up
# clarification. The rest of the prompt (zone structure, coverage,
# resolution, qualifier, ambiguity, similarity, output-field guidance)
# applies identically once the merged intent is in hand.
# ---------------------------------------------------------------------------

_CLARIFICATION_TASK_AND_OUTCOME = """\
You route a movie search query into one of seven entity-flow \
outcomes and decide whether the standard (descriptor-based) flow \
should co-fire. The user has supplied TWO inputs: an original query \
and a follow-up clarification correcting or refining it. Treat the \
two together as a single search intent.
- The clarification is authoritative on any conflict with the \
  original — when they disagree, the clarification wins.
- The original is preserved where the clarification is silent — the \
  user has not retracted material the clarification does not touch.
- When the clarification retracts part of the original, drop that \
  material from the search intent before routing.
- A clarification can shift the flow entirely. If the original \
  pointed at an entity flow but the clarification turns the search \
  into an attribute-shaped ask (or vice versa), re-evaluate the flow \
  from the merged intent — do not anchor on what the original alone \
  would have routed to.

The entity-flow outcomes are mutually exclusive — pick exactly one:

- specific_title — the merged intent, as expressed, IS a film title. \
  Resolve canonical_name to the most common canonical form of the \
  title and let the downstream search fan out — it surfaces every \
  film sharing that title, remakes, and lineage entries \
  automatically. A stated year sharpens intent toward that specific \
  installment.
- similarity_to_titles — the merged intent is a similarity frame \
  pointing at one or more reference films, either an explicit frame \
  ("movies like X") or a bare list of two or more film titles with \
  no other content
- character_franchise — the merged intent, as expressed, IS the name \
  of a character whose identity persists across multiple films
- non_character_franchise — the merged intent, as expressed, IS the \
  name of a series, property, or IP umbrella
- studio — the merged intent, as expressed, IS the name of one or \
  more film studios / production companies
- person — the merged intent, as expressed, IS the name of one or \
  more real humans credited in films in any filmmaking role: actor, \
  director, writer, producer, or composer. No preferred role.
- none_of_the_above — the merged intent does not cleanly resolve to \
  any of the above

Your job is:
- observe every entity-shaped span across both inputs and classify \
  each by kind
- observe every non-entity descriptor phrase across both inputs as a \
  qualifier
- merge the two inputs into a single search intent per the \
  authoritative-clarification rule above
- pick the single mutually-exclusive entity flow the merged intent \
  belongs to (or none_of_the_above)
- reason about whether the chosen entity reading has a genuinely \
  defensible non-entity primary reading of comparable likelihood, \
  and set the standard-co-fire boolean accordingly

Your job is NOT:
- to rewrite or paraphrase either input into a single combined \
  string
- to enrich the merged intent with proxy traits, quality signals, \
  or inferred narrowings the user did not state
- to invent titles, characters, franchises, studios, or people \
  from descriptions — only recognize entities the inputs are \
  already pointing to
- to decide whether the standard flow fires when no entity was \
  chosen — that case is handled in code

---

"""


CLARIFICATION_SYSTEM_PROMPT = (
    _CLARIFICATION_TASK_AND_OUTCOME
    + _ZONE_STRUCTURE
    + _COVERAGE_PRINCIPLE
    + _RESOLUTION_PRINCIPLE
    + _QUALIFIER_RULE
    + _AMBIGUITY_PRINCIPLE
    + _SIMILARITY_FRAME_RULE
    + _OUTPUT_FIELD_GUIDANCE
)


# Step 0 is pinned to Gemini 3.5 Flash with minimal thinking
# (`thinking_level="minimal"` — the lowest non-disabled level, below
# "low") and a very low temperature. Flow routing runs on every
# query and is latency-sensitive, so we standardize on the fastest
# reliable backend. With the tighter taxonomy and Rich-fields
# teaching, prose variation is not load-bearing — a more
# deterministic classifier is what we want.
_STEP_0_PROVIDER = LLMProvider.GEMINI
_STEP_0_MODEL = "gemini-3.5-flash"
_STEP_0_KWARGS: dict = {
    "thinking_config": {"thinking_level": "minimal"},
    "temperature": 0.1,
}


async def run_step_0(
    query: str,
    clarification: str | None = None,
) -> tuple[Step0Response, int, int]:
    """Route a raw user query into search flows via LLM structured output.

    Provider, model, and provider-specific kwargs are fixed at the
    module level (see _STEP_0_PROVIDER/_MODEL/_KWARGS) because step 0
    runs on every query and we want a single stable configuration.

    Args:
        query: the raw user search query (non-empty after stripping).
        clarification: optional follow-up clarification text the user
            supplied to correct or refine the original query. When
            present, swaps in the clarification-mode system prompt and
            passes both inputs as separate labeled fields so the model
            can resolve precedence deterministically (clarification
            wins on conflict). When None, behavior is identical to the
            no-clarification path.

    Returns:
        A tuple of (Step0Response, input_tokens, output_tokens).
    """
    query = query.strip()
    if not query:
        raise ValueError("query must be a non-empty string.")

    clarification = clarification.strip() if clarification else None

    if clarification:
        # Two labeled fields, not concatenated — the system prompt
        # teaches the model how to resolve precedence between them.
        user_prompt = (
            f"Original query: {query}\n"
            f"Clarification: {clarification}"
        )
        system_prompt = CLARIFICATION_SYSTEM_PROMPT
    else:
        user_prompt = f"Query: {query}"
        system_prompt = SYSTEM_PROMPT

    response, input_tokens, output_tokens = await generate_llm_response_async(
        provider=_STEP_0_PROVIDER,
        user_prompt=user_prompt,
        system_prompt=system_prompt,
        response_format=Step0Response,
        model=_STEP_0_MODEL,
        **_STEP_0_KWARGS,
    )

    return response, input_tokens, output_tokens
