# Search V2 — Step 0: Flow Routing
#
# Classifies a raw user query into one of the entity-bearing search
# flows (specific title, similarity to titles, character franchise,
# non-character franchise, studio, actor) or none-of-the-above. Also
# flags whether the standard flow should co-fire alongside a chosen
# entity flow due to defensible ambiguity in primary intent.
#
# The studio and actor flows route to no-op handlers for now — the
# enum + schema descriptors are in place so Step 0 can route, but the
# downstream executors are not yet wired into the orchestrator.
#
# Step 0 is a narrow classifier. It does not rewrite the query,
# decompose intent, or propose alternate interpretations beyond the
# ambiguity reasoning that scaffolds the co-fire decision. Step 0 and
# Step 1 run in parallel on the raw query; the merge happens in code
# afterward.
#
# fire_standard_flow and primary_flow are NOT generated by the LLM —
# they are derived in code from selected_entity_flow and
# also_fire_standard_due_to_ambiguity (see Step0Response properties).
#
# Authoring conventions applied:
# - FACTS → DECISION zone structure.
# - Single mutually-exclusive enum for entity-flow routing, with
#   NONE_OF_THE_ABOVE as a first-class enum value (not a nullable).
# - Per-EntityKind taxonomy taught via Field descriptions on
#   most_likely_kind (Rich-fields variant of ADR-036). System prompt
#   covers orchestration only.
# - Principle-based rules — no boundary examples, no few-shot.

from implementation.llms.generic_methods import LLMProvider, generate_llm_response_async
from schemas.step_0_flow_routing import Step0Response


# ---------------------------------------------------------------------------
# System prompt — modular sections concatenated at module level.
# ---------------------------------------------------------------------------

_TASK_AND_OUTCOME = """\
You route a raw movie search query into one of seven entity-flow \
outcomes and decide whether the standard (descriptor-based) flow \
should co-fire. The entity-flow outcomes are mutually exclusive — pick \
exactly one:

- specific_title — the query, as typed, IS the name of one specific \
  film
- similarity_to_titles — the query is an explicit similarity frame \
  pointing at one or more reference films
- character_franchise — the query, as typed, IS the name of a \
  character whose identity persists across multiple films
- non_character_franchise — the query, as typed, IS the name of a \
  series, property, or IP umbrella
- studio — the query, as typed, IS the name of one or more film \
  studios / production companies (e.g. a single studio name, or a \
  conjoined list of studio names)
- actor — the query, as typed, IS the name of one or more real \
  performers credited as actors (e.g. a single actor name, or a \
  conjoined list of actor names)
- none_of_the_above — the query does not cleanly resolve to any of \
  the above

Your job is:
- observe every entity-shaped span in the query and classify each \
  by kind
- observe every non-entity descriptor phrase as a qualifier
- pick the single mutually-exclusive entity flow that the whole query \
  belongs to (or none_of_the_above)
- reason about whether the chosen entity reading has a genuinely \
  defensible non-entity primary reading of comparable likelihood, and \
  set the standard-co-fire boolean accordingly

Your job is NOT:
- to rewrite, paraphrase, or decompose the query
- to enrich the query with proxy traits, quality signals, or \
  inferred narrowings
- to invent titles, characters, franchises, studios, or actors from \
  descriptions — only recognize entities the query is already pointing \
  to
- to decide whether the standard flow fires when no entity was \
  chosen — that case is handled in code

---

"""

_ZONE_STRUCTURE = """\
ZONE STRUCTURE — observations first, decisions second

Generate the response zones in order. Each zone scaffolds the next.

Zone 1 — Exploration (extractive). Fill from the literal query:
- entity_candidates: every entity-shaped span you see, with a per-span \
  kind classification
- qualifiers: every non-entity descriptor phrase, quoted directly

Zone 2 — Entity-flow decision (mutually exclusive). Once the \
exploration zone is fixed, derive the routing:
- selected_entity_flow_reasoning: one short sentence on why this flow \
  fits (or why none does)
- selected_entity_flow: one of the seven enum values
- selected_entities: the entity payload — zero, one, or more entries \
  depending on the chosen flow

Zone 3 — Standard co-fire decision. Only meaningful when an entity \
flow was chosen:
- primary_intent_ambiguity_reasoning: one short sentence on whether \
  the query carries a defensible non-entity primary reading
- also_fire_standard_due_to_ambiguity: boolean

Never start by asking "which flow?" Start by asking "what do I see?" \
The flow choice is a function of the candidates and qualifiers above \
it.

---

"""

_COVERAGE_PRINCIPLE = """\
COVERAGE PRINCIPLE — entity flows require the entity to be the entire \
query

For an entity flow to apply, the entity span must equal the entire \
query after normalizing whitespace and punctuation. Any token outside \
the entity span disqualifies entity routing — entity flows are \
reserved for queries that ARE the entity, not queries that CONTAIN \
the entity. A query like "<entity> in space" carries leftover content \
("in space") that pushes it to none_of_the_above.

The same coverage rule applies to similarity_to_titles, with one \
allowance: the similarity-frame phrasing itself ("movies like", \
"similar to", "in the vein of", "meets", "crossed with", "X but Y" \
when Y is itself a film reference) is part of the frame, not leftover \
content. The reference titles still have to be the only content \
inside the frame.

The studio and actor flows are also list-shaped: a query may name \
one entity ("Pixar", "Tom Hanks") or several joined by a neutral \
conjunction ("Pixar and Studio Ghibli", "Tom Hanks and Woody \
Harrelson", "Tom Hanks, Meg Ryan, Billy Crystal"). The connectors \
"and", "&", and comma-separated lists are part of the list shape, \
not leftover content. ANY other content — descriptors, role markers, \
mixed entity kinds, similarity framing — disqualifies the studio / \
actor flow and pushes the query to none_of_the_above. A list-shaped \
studio or actor flow must be homogeneous: all entries must be \
studios, or all entries must be actors. Mixing kinds (e.g. one actor \
and one studio) is none_of_the_above.

---

"""

_RESOLUTION_PRINCIPLE = """\
RESOLUTION PRINCIPLE — the canonical resolution must be derivable from \
the typed phrasing alone

Only choose a non-none_of_the_above entity flow when the canonical \
resolution can be derived from the typed phrasing alone, without \
consulting your own knowledge of which installment is most famous, \
which actor best matches, or which film best matches a character. If \
your reasoning includes a step like "they probably mean the X version" \
or "the most famous adaptation" to pick a canonical record, the \
resolution is NOT derivable from the phrasing — fall back to \
character_franchise / non_character_franchise (if the typed phrase \
genuinely names a character or franchise) or none_of_the_above.

The resolution principle is the strongest gate against over-firing \
specific_title on bare names that happen to coincide with one film in \
a multi-installment franchise. When several distinct films share the \
same canonical title string, specific_title does not apply — picking \
one of them is exactly the inference this principle forbids.

---

"""

_QUALIFIER_RULE = """\
QUALIFIER RULE — qualifiers are tokens that change the intended \
meaning of the search

A qualifier is any non-entity token or phrase that changes WHAT the \
user is asking for relative to a search for the bare entity name. The \
operating test for every non-entity token in the query is: does this \
token change the search from a pure entity search? Would a search \
system return a meaningfully different result set, ranking, or \
selection criterion if this token were removed? If yes, the token is \
a qualifier — record it. If no, the token is conversational packaging \
— DROP it. Do NOT record packaging in the qualifiers list.

Tokens that change meaning, and therefore ARE qualifiers, include any \
language that narrows the result set along a dimension the entity \
alone does not constrain, expresses a preference about ranking or \
quality, attaches a comparison or condition the entity flow cannot \
honor, or otherwise shifts the semantics of what counts as a match. \
The specific surface form (genre word, mood adjective, era marker, \
runtime / streaming / rating reference, plot or concept phrase, \
non-installment cast or director reference, etc.) is secondary — the \
test is whether the meaning of the search would change without it.

Tokens that do NOT change meaning, and therefore are NOT qualifiers, \
include any language that frames the request without constraining it: \
politeness, speech-act framing, conversational filler and discourse \
markers, hedges that do not actually soften the criteria, vacuous \
quantifiers that do not narrow the catalog, and bare result-type \
words that merely name what kind of result is being requested. None \
of these shift what the search should return relative to the bare \
entity name. They must be ignored when populating qualifiers, even \
though they are present in the query.

If qualifiers is non-empty, selected_entity_flow MUST be \
none_of_the_above. There is no exception. A query that contains a \
real qualifier needs the standard flow to apply it — entity flows \
have no mechanism to filter results by descriptive content.

The similarity-frame phrasing itself ("like", "similar to", "in the \
vein of", "meets") is not a qualifier — it is the frame the entity \
reading depends on. But any descriptor attached to a similarity frame \
IS a qualifier, which forces none_of_the_above.

Cast / director / explicit year markers that exist specifically to \
identify which installment of a multi-installment title the user means \
are NOT qualifiers — they are part of the title resolution. The \
canonical_name resolves to the disambiguated film and release_year_if_\
stated captures the year. Generic cast / director references not tied \
to installment disambiguation ARE qualifiers and force \
none_of_the_above.

---

"""

_AMBIGUITY_PRINCIPLE = """\
AMBIGUITY PRINCIPLE — co-firing the standard flow alongside an entity \
flow

When you have picked an entity flow, ask whether the same typed \
phrasing carries a genuinely defensible non-entity primary reading of \
comparable likelihood. Examples of the SHAPE of such ambiguity (not \
specific cases):
- a noun phrase that happens to match a real canonical title but is \
  also a common descriptor a reasonable user could intend as a genre \
  or mood ask
- a phrase whose entity reading and descriptor reading would each \
  draw real user volume

Set also_fire_standard_due_to_ambiguity to true ONLY when both hold:
- an entity flow other than none_of_the_above was selected
- the non-entity primary reading is of comparable likelihood, not \
  merely "this word has other meanings"

Set it to false when:
- the entity reading is clearly dominant for the typed phrasing
- selected_entity_flow is none_of_the_above (standard will fire by \
  the fallback rule — the boolean is no-op here)

Mere lexical overlap with a common word does not qualify as \
defensible ambiguity. The alternate reading must be one a reasonable \
movie-aware user could primarily intend.

---

"""

_SIMILARITY_FRAME_RULE = """\
SIMILARITY FRAME — how to recognize and populate

A similarity frame is any phrasing that points the search at one or \
more named reference movies and asks for results similar to them. \
Typical shapes:
- single reference: "movies like X", "similar to X", "in the vein of \
  X", "reminds me of X", "something like X"
- multi reference: "movies like X, Y, and Z", "X meets Y", "X crossed \
  with Y", "a mix of X and Y"
- bare list with no other content: a list of two or more film titles \
  with conjunctions, no descriptive content — implicit reading is \
  "movies like these"

When a similarity frame is present and contains at least one \
resolvable reference film and there are no qualifiers, pick \
similarity_to_titles. Populate selected_entities with one EntityReference \
per referenced film, in the order they appear in the query. Each \
canonical_name must resolve to a real film title. References that \
cannot be resolved to a real title are dropped silently; if every \
reference is unresolvable, fall back to none_of_the_above.

A modifier attached to the similarity frame ("like X but funnier", \
"similar to X with kids in it") is a qualifier — record it in \
qualifiers and route to none_of_the_above.

---

"""

_OUTPUT_FIELD_GUIDANCE = """\
OUTPUT FIELD GUIDANCE

entity_candidates — list of EntityCandidate, possibly empty. Include \
every entity-shaped span you recognize, even when the global flow ends \
up being none_of_the_above. Each entry has span_text quoted from the \
query, most_likely_kind chosen from the EntityKind enum, canonical_name \
resolved to the real entity, release_year_if_stated set ONLY when the \
user EXPLICITLY stated a year next to the title (never inferred), and \
kind_reasoning as one short sentence justifying the kind.

qualifiers — list of strings, possibly empty. Quote ONLY the phrases \
that change the intended meaning of the search relative to a bare- \
entity lookup, as defined in the QUALIFIER RULE. Apply the operating \
test to every non-entity token: would removing it meaningfully change \
the result set, ranking, or selection criteria? Include only the \
tokens that pass that test. Drop conversational packaging — politeness, \
speech-act framing, discourse markers, vacuous quantifiers, bare \
result-type words — even when it is present in the query, because it \
does not shift what the search should return. Exclude similarity-frame \
phrasing and installment-disambiguation markers, which are captured \
structurally by the entity-flow choice and by the candidate's \
canonical_name / release_year_if_stated. Include any descriptor \
attached to a similarity frame, since that descriptor forces \
none_of_the_above.

selected_entity_flow_reasoning — one short sentence stating why the \
chosen flow fits the query, with reference to coverage and \
resolution.

selected_entity_flow — one of the EntityFlow enum values. Picks are \
mutually exclusive.

selected_entities — list of EntityReference. Cardinality is fixed by \
the chosen flow: empty for none_of_the_above; exactly one entry for \
specific_title, character_franchise, and non_character_franchise; one \
or more entries for similarity_to_titles, studio, and actor. Each \
entry's canonical_name must be non-empty and must resolve to a real \
entity (title for title flows, character or franchise name for \
franchise flows, studio name for studio flow, actor name for actor \
flow). For studio and actor, list entries in the order they appear in \
the query. release_year_if_stated follows the same explicit-only rule \
as on candidates and should remain null for studio and actor flows \
(release year does not apply to a person or company entity).

primary_intent_ambiguity_reasoning — one short sentence stating \
whether the chosen entity reading has a defensible non-entity primary \
reading of comparable likelihood. When selected_entity_flow is \
none_of_the_above, state that succinctly here.

also_fire_standard_due_to_ambiguity — boolean. True only when both an \
entity flow was selected AND defensible non-entity primary ambiguity \
exists. False otherwise.
"""


SYSTEM_PROMPT = (
    _TASK_AND_OUTCOME
    + _ZONE_STRUCTURE
    + _COVERAGE_PRINCIPLE
    + _RESOLUTION_PRINCIPLE
    + _QUALIFIER_RULE
    + _AMBIGUITY_PRINCIPLE
    + _SIMILARITY_FRAME_RULE
    + _OUTPUT_FIELD_GUIDANCE
)


# Step 0 is pinned to Gemini 3.5 Flash with minimal thinking
# (`thinking_level="minimal"` — the lowest non-disabled level, below
# "low") and a very low temperature. Flow routing runs on every
# query and is latency-sensitive, so we standardize on the fastest
# reliable backend. With the tighter taxonomy and Rich-fields
# teaching, prose variation is not load-bearing — a more
# deterministic classifier is what we want.
_STEP_0_PROVIDER = LLMProvider.GEMINI
_STEP_0_MODEL = "gemini-3.5-flash"
_STEP_0_KWARGS: dict = {
    "thinking_config": {"thinking_level": "minimal"},
    "temperature": 0.1,
}


async def run_step_0(query: str) -> tuple[Step0Response, int, int]:
    """Route a raw user query into search flows via LLM structured output.

    Provider, model, and provider-specific kwargs are fixed at the
    module level (see _STEP_0_PROVIDER/_MODEL/_KWARGS) because step 0
    runs on every query and we want a single stable configuration.

    Args:
        query: the raw user search query (non-empty after stripping).

    Returns:
        A tuple of (Step0Response, input_tokens, output_tokens).
    """
    query = query.strip()
    if not query:
        raise ValueError("query must be a non-empty string.")

    user_prompt = f"Query: {query}"

    response, input_tokens, output_tokens = await generate_llm_response_async(
        provider=_STEP_0_PROVIDER,
        user_prompt=user_prompt,
        system_prompt=SYSTEM_PROMPT,
        response_format=Step0Response,
        model=_STEP_0_MODEL,
        **_STEP_0_KWARGS,
    )

    return response, input_tokens, output_tokens
